version: '2'
services:
  mysql:
  # https://github.com/docker-library/docs/blob/master/mysql/README.md
    image: mysql/mysql-server:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # mysql access root/root
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME} #Customize your database name
      MYSQL_USER: ${COMPOSE_PROJECT_NAME}
      MYSQL_PASSWORD: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    #volumes:
    #  - ./mysql:/etc/my.cnf.d/
    ports:
      - "3306:3306"
  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - "6379:6379"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql
    environment:
        PMA_HOST: mysql
        PMA_USER: ${COMPOSE_PROJECT_NAME}
        PMA_PASSWORD: ${COMPOSE_PROJECT_NAME}
    ports:
      - ${PHPMYADMIN_PORT}:80
  #solr:
  #  image: solr:5.3
  #  ports:
  #    - "8983:8983"
  mail:
    # https://hub.docker.com/r/mailhog/mailhog/
    image: mailhog/mailhog
    ports:
     - "1025:1025"
     - "${MAILHOG_PORT}:8025"
  #varnish:
  #  image: biko2/docker-varnish:4.0
  #  ports:
  #   - "80:80"
  #    - "6082:6082"
  #  volumes:
  #    - ./config/varnish/drupal-base.vcl:/etc/varnish/default.vcl
  #  # environment:
  #    # - VARNISH_PORT=80
  #    # - VARNISH_MEMORY=500M
  #    # Next values only works with default default.vcl file.
  #    # - VARNISH_BACKEND_IP=web
  #    # - VARNISH_BACKEND_PORT=80
  web:
    image: biko2/apache-php:${PHP_VERSION}
    #image: biko2/apache-php:5.6 ##Fallback, por si echamos atrás la versión de php
    depends_on:
      - mysql
      - mail
      - redis
    ports:
     - "${WEB_PORT}:80"
     - "${WEB_PORT_SSL}:443"
     - "2222:22"
    volumes:
     - ./vhosts:/etc/apache2/sites-enabled
     - ./vhosts/certs/docker.crt:/etc/ssl/docker.crt
     - ./vhosts/certs/docker.key:/etc/ssl/docker.key
     - ${WEB_ROOT}:/var/www/html
     #  - ./php7.0/php.ini:/etc/php/apache2/php.ini
     #  - ./php7.0/xdebug.ini:/etc/php/7.0/apache2/conf.d/20-xdebug.ini
     #- ~/.drush:/root/.drush ## drush config
     #- ~/.ssh:/root/.ssh ## ssh config
    links:
     - mysql
     - mail
     - redis
   # - solr
#  gulp:
#      build:
#        context: ./gulp/
#        # Environment variables
#        args:
#          - USER
#          - USER_ID
#      ports:
#          - 8082:9000
#      volumes:
#          - .:/var/www/html
#      working_dir: /var/www/html/web/themes/custom/tema-base
